spring.application.name=companie-aerienne

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

spring.datasource.url=jdbc:postgresql://localhost:5432/testa
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.connection.characterEncoding=UTF-8
spring.jpa.properties.hibernate.connection.useUnicode=true
# Génération automatique du schéma (tables) à partir des entités
spring.jpa.hibernate.ddl-auto=update
# (Optionnel) Afficher les requêtes SQL de Hibernate dans la console
spring.jpa.show-sql=true
